FROM node:18.0.0

WORKDIR /app

RUN npm install -g pnpm@9.15.3

COPY package.json pnpm-workspace.yaml pnpm-lock.yaml ./
COPY packages/frontend/package.json ./packages/frontend/package.json

RUN pnpm install

COPY . .

CMD [ "pnpm", "run", "dev" ]
